apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rybbit
  namespace: flux-system
spec:
  suspend: false
  interval: 1m0s
  path: ./rybbit
  prune: false
  force: false
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
