apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cs16-surf
  namespace: flux-system
spec:
  suspend: true
  interval: 1m0s
  path: ./cs16-surf-pi/infra/production
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
